### ISSUE TITLE
Stranded Kids patch causes the cave area tiles to be scrambled. 

### ISSUE THREAD

**Issue by SpookySquidGames** [jduckett95/infinest-pocket-patches#3]
When you reach the cave in Stranded Kids the tiles are clearly scrambled. Everything else seems to work in that area, it's purely a graphical issue. Since it can take awhile to reach that spot in the game I've attached my pocket save file, just rename ".txt" to ".sav" github wouldn't let me upload the file with the .sav extension. To reach the cave from the hut go North, West, North, North.
Hope that helps! 

[Stranded Kids.txt](https://github.com/jduckett95/infinest-pocket-patches/files/7836848/Stranded.Kids.txt)

**Comment by Infinest** [comment]
Hey there,

thanks for reporting the issue and thanks for the save file.
It's always a bit difficult if the issue is deeper into the game and no save file is attached.
For  your convenience here's the updated version. @jduckett95 should update the repository soon.

[Stranded Kids Analogue Pocket patch v1.1.zip](https://github.com/jduckett95/infinest-pocket-patches/files/7841072/Stranded.Kids.Analogue.Pocket.patch.v1.1.zip)

**Comment by jduckett95** [comment]
https://github.com/jduckett95/infinest-pocket-patches/blob/main/README.md#stranded-kids Fix released

**Comment by SpookySquidGames** [comment]
Wow thanks for the quick fix! I'll check it out tonight! Glad the save file was helpful!
